This notebook is used to turn the collected data into something more useable and consumable. I turned what I collected into various different statistical catagories that will help my model become more accurate at prediction. This could not have been possible without using K1NG's Overwatch League Spreadsheet. You can find it here:
https://docs.google.com/spreadsheets/d/1KJGwLRMDJP1SSakt25laZbDaTNYRHZYHJmV6rh86jnc/edit?usp=sharing

Note: This is updated to include the 2020 season and the statslab format.

In [1]:
#Getting proper libraries
import pandas as pd
import numpy as np
import re
import requests, zipfile, io
from bs4 import BeautifulSoup

In [2]:
#Getting List of Map Types
from constants import MAP_TYPE

In [3]:
#This scrapes the data and automatically gets the latest csv as they get released
from selenium.webdriver import Chrome
path = "chromedriver.exe"
driver = Chrome(path)
driver.get("https://overwatchleague.com/en-us/statslab")
player_stats = driver.find_element_by_xpath('//*[@id="__next"]/div/div/div[4]/div/ul/li[3]/a').get_attribute('href')
match_stats = driver.find_element_by_xpath('//*[@id="__next"]/div/div/div[4]/div/ul/li[4]/a').get_attribute('href')
driver.close()

#get match stats
dataurl = match_stats
r = requests.get(dataurl)
z = zipfile.ZipFile(io.BytesIO(r.content))
z.extractall()

In [10]:
#Reads the CSV and loads it into a dataframe
df= pd.read_csv("match_map_stats.csv")

#This splits the data into different years for more precise data
match2018 = df[df["round_end_time"].str.contains("2018")]
match2019 = df[df["round_end_time"].str.contains("2019")]
match2020 = df[df["round_end_time"].str.contains("2020")]

#selecting which one to use
df = match2019

#This can be used to combine different years
#df = pd.concat([match2018, match2019])

#Created a Filtration System to filter out certain stats
df = df[~df.stage.str.contains("Post-Season")]

,round_start_time,round_end_time,stage,match_id,game_number,match_winner,map_winner,map_loser,map_name,map_round,...,team_one_name,team_two_name,attacker_payload_distance,defender_payload_distance,attacker_time_banked,defender_time_banked,attacker_control_perecent,defender_control_perecent,attacker_round_end_score,defender_round_end_score
2678,2/15/2019 0:11,2/15/2019 0:14,Overwatch League Stage 1,21211,1,Philadelphia Fusion,Philadelphia Fusion,London Spitfire,Ilios,1,...,Philadelphia Fusion,London Spitfire,0.000000,0.000000,0.000000,0.000000,57.0,100.0,0,1
2679,2/15/2019 0:15,2/15/2019 0:18,Overwatch League Stage 1,21211,1,Philadelphia Fusion,Philadelphia Fusion,London Spitfire,Ilios,2,...,Philadelphia Fusion,London Spitfire,0.000000,0.000000,0.000000,0.000000,100.0,0.0,1,1
2680,2/15/2019 0:19,2/15/2019 0:23,Overwatch League Stage 1,21211,1,Philadelphia Fusion,Philadelphia Fusion,London Spitfire,Ilios,3,...,Philadelphia Fusion,London Spitfire,0.000000,0.000000,0.000000,0.000000,100.0,27.0,2,1
2681,2/15/2019 0:27,2/15/2019 0:35,Overwatch League Stage 1,21211,2,Philadelphia Fusion,Philadelphia Fusion,London Spitfire,Hollywood,1,...,London Spitfire,Philadelphia Fusion,72.082550,0.000000,0.000000,0.000000,NaN,NaN,2,0
2682,2/15/2019 0:38,2/15/2019 0:46,Overwatch League Stage 1,21211,2,Philadelphia Fusion,Philadelphia Fusion,London Spitfire,Hollywood,2,...,London Spitfire,Philadelphia Fusion,66.118507,72.082550,0.000000,0.000000,NaN,NaN,2,3
2683,2/15/2019 0:59,2/15/2019 1:03,Overwatch League Stage 1,21211,3,Philadelphia Fusion,London Spitfire,Philadelphia Fusion,Volskaya Industries,1,...,Philadelphia Fusion,London Spitfire,0.000000,0.000000,226.507980,0.000000,NaN,NaN,2,0
2684,2/15/2019 1:06,2/15/2019 1:11,Overwatch League Stage 1,21211,3,Philadelphia Fusion,London Spitfire,Philadelphia Fusion,Volskaya Industries,2,...,Philadelphia Fusion,London Spitfire,0.000000,0.000000,215.071014,226.507980,NaN,NaN,2,2
2685,2/15/2019 1:12,2/15/2019 1:17,Overwatch League Stage 1,21211,3,Philadelphia Fusion,London Spitfire,Philadelphia Fusion,Volskaya Industries,3,...,Philadelphia Fusion,London Spitfire,0.000000,0.000000,0.000000,226.507980,NaN,NaN,4,2
2686,2/15/2019 1:19,2/15/2019 1:21,Overwatch League Stage 1,21211,3,Philadelphia Fusion,London Spitfire,Philadelphia Fusion,Volskaya Industries,4,...,Philadelphia Fusion,London Spitfire,0.000000,0.000000,115.059975,0.000000,NaN,NaN,4,4
2687,2/15/2019 1:22,2/15/2019 1:25,Overwatch League Stage 1,21211,3,Philadelphia Fusion,London Spitfire,Philadelphia Fusion,Volskaya Industries,5,...,Philadelphia Fusion,London Spitfire,0.000000,0.000000,0.000000,0.000000,NaN,NaN,5,4
2688,2/15/2019 1:28,2/15/2019 1:33,Overwatch League Stage 1,21211,4,Philadelphia Fusion,Philadelphia Fusion,London Spitfire,Rialto,1,...,Philadelphia Fusion,London Spitfire,43.572945,0.000000,0.000000,0.000000,NaN,NaN,0,0
2689,2/15/2019 1:35,2/15/2019 1:36,Overwatch League Stage 1,21211,4,Philadelphia Fusion,Philadelphia Fusion,London Spitfire,Rialto,2,...,Philadelphia Fusion,London Spitfire,43.577850,43.572945,185.332001,0.000000,NaN,NaN,1,0
2690,2/15/2019 1:54,2/15/2019 2:00,Overwatch League Stage 1,21221,1,New York Excelsior,New York Excelsior,Boston Uprising,Nepal,1,...,New York Excelsior,Boston Uprising,0.000000,0.000000,0.000000,0.000000,100.0,99.0,1,0
2691,2/15/2019 2:00,2/15/2019 2:04,Overwatch League Stage 1,21221,1,New York Excelsior,New York Excelsior,Boston Uprising,Nepal,2,...,New York Excelsior,Boston Uprising,0.000000,0.000000,0.000000,0.000000,100.0,64.0,2,0
2692,2/15/2019 2:08,2/15/2019 2:15,Overwatch League Stage 1,21221,2,New York Excelsior,Boston Uprising,New York Excelsior,Numbani,1,...,New York Excelsior,Boston Uprising,71.795654,0.000000,38.579037,0.000000,NaN,NaN,3,0
2693,2/15/2019 2:18,2/15/2019 2:23,Overwatch League Stage 1,21221,2,New York Excelsior,Boston Uprising,New York Excelsior,Numbani,2,...,New York Excelsior,Boston Uprising,71.804321,71.795654,208.820999,60.000000,NaN,NaN,3,3
2694,2/15/2019 2:24,2/15/2019 2:26,Overwatch League Stage 1,21221,2,New York Excelsior,Boston Uprising,New York Excelsior,Numbani,3,...,New York Excelsior,Boston Uprising,66.770546,71.804321,0.000000,208.820999,NaN,NaN,4,3
2695,2/15/2019 2:27,2/15/2019 2:32,Overwatch League Stage 1,21221,2,New York Excelsior,Boston Uprising,New York Excelsior,Numbani,4,...,New York Excelsior,Boston Uprising,0.000000,66.770546,0.000000,0.000000,NaN,NaN,3,4
2696,2/15/2019 2:41,2/15/2019 2:46,Overwatch League Stage 1,21221,3,New York Excelsior,draw,draw,Horizon Lunar Colony,1,...,New York Excelsior,Boston Uprising,0.000000,0.000000,170.417007,0.000000,NaN,NaN,2,0
2697,2/15/2019 2:49,2/15/2019 2:54,Overwatch League Stage 1,21221,3,New York Excelsior,draw,draw,Horizon Lunar Colony,2,...,New York Excelsior,Boston Uprising,0.000000,0.000000,186.737000,170.417007,NaN,NaN,2,2
2698,2/15/2019 2:56,2/15/2019 2:58,Overwatch League Stage 1,21221,3,New York Excelsior,draw,draw,Horizon Lunar Colony,3,...,New York Excelsior,Boston Uprising,0.000000,0.000000,44.038017,186.737000,NaN,NaN,4,2
2699,2/15/2019 3:00,2/15/2019 3:02,Overwatch League Stage 1,21221,3,New York Excelsior,draw,draw,Horizon Lunar Colony,4,...,New York Excelsior,Boston Uprising,0.000000,0.000000,84.852989,60.000000,NaN,NaN,4,4
2700,2/15/2019 3:04,2/15/2019 3:05,Overwatch League Stage 1,21221,3,New York Excelsior,draw,draw,Horizon Lunar Colony,5,...,New York Excelsior,Boston Uprising,0.000000,0.000000,0.000000,84.852989,NaN,NaN,4,4
2701,2/15/2019 3:06,2/15/2019 3:08,Overwatch League Stage 1,21221,3,New York Excelsior,draw,draw,Horizon Lunar Colony,6,...,New York Excelsior,Boston Uprising,0.000000,0.000000,0.000000,0.000000,NaN,NaN,4,4
2702,2/15/2019 3:12,2/15/2019 3:20,Overwatch League Stage 1,21221,4,New York Excelsior,New York Excelsior,Boston Uprising,Route 66,1,...,New York Excelsior,Boston Uprising,60.873276,0.000000,0.000000,0.000000,NaN,NaN,2,0
2703,2/15/2019 3:22,2/15/2019 3:28,Overwatch League Stage 1,21221,4,New York Excelsior,New York Excelsior,Boston Uprising,Route 66,2,...,New York Excelsior,Boston Uprising,60.874603,60.873276,79.700027,0.000000,NaN,NaN,3,2
2704,2/15/2019 3:46,2/15/2019 3:51,Overwatch League Stage 1,21231,1,Seoul Dynasty,Los Angeles Gladiators,Seoul Dynasty,Ilios,1,...,Seoul Dynasty,Los Angeles Gladiators,0.000000,0.000000,0.000000,0.000000,48.0,100.0,0,1
2705,2/15/2019 3:51,2/15/2019 3:54,Overwatch League Stage 1,21231,1,Seoul Dynasty,Los Angeles Gladiators,Seoul Dynasty,Ilios,2,...,Seoul Dynasty,Los Angeles Gladiators,0.000000,0.000000,0.000000,0.000000,0.0,100.0,0,2
2706,2/15/2019 3:58,2/15/2019 4:05,Overwatch League Stage 1,21231,2,Seoul Dynasty,Seoul Dynasty,Los Angeles Gladiators,King's Row,1,...,Los Angeles Gladiators,Seoul Dynasty,70.287689,0.000000,102.083023,0.000000,NaN,NaN,3,0
2707,2/15/2019 4:07,2/15/2019 4:14,Overwatch League Stage 1,21231,2,Seoul Dynasty,Seoul Dynasty,Los Angeles Gladiators,King's Row,2,...,Los Angeles Gladiators,Seoul Dynasty,101.678505,70.287689,0.000000,102.083023,NaN,NaN,1,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5941,8/25/2019 20:05,8/25/2019 20:09,Overwatch League Stage 4,21514,3,Hangzhou Spark,Hangzhou Spark,Shanghai Dragons,Hollywood,2,...,Hangzhou Spark,Shanghai Dragons,33.721497,33.717171,246.923004,0.000000,NaN,NaN,3,2
5942,8/25/2019 20:16,8/25/2019 20:22,Overwatch League Stage 4,21514,4,Hangzhou Spark,Hangzhou Spark,Shanghai Dragons,Havana,1,...,Shanghai Dragons,Hangzhou Spark,103.371460,0.000000,132.798996,0.000000,NaN,NaN,3,0
5943,8/25/2019 20:24,8/25/2019 20:31,Overwatch League Stage 4,21514,4,Hangzhou Spark,Hangzhou Spark,Shanghai Dragons,Havana,2,...,Shanghai Dragons,Hangzhou Spark,48.285584,103.371460,0.000000,132.798996,NaN,NaN,1,3
5944,8/25/2019 20:46,8/25/2019 20:48,Overwatch League Stage 4,21446,1,Atlanta Reign,Atlanta Reign,Boston Uprising,Lijiang Tower,1,...,Atlanta Reign,Boston Uprising,0.000000,0.000000,0.000000,0.000000,100.0,0.0,1,0
5945,8/25/2019 20:49,8/25/2019 20:54,Overwatch League Stage 4,21446,1,Atlanta Reign,Atlanta Reign,Boston Uprising,Lijiang Tower,2,...,Atlanta Reign,Boston Uprising,0.000000,0.000000,0.000000,0.000000,100.0,50.0,2,0
5946,8/25/2019 20:59,8/25/2019 21:06,Overwatch League Stage 4,21446,2,Atlanta Reign,Atlanta Reign,Boston Uprising,Volskaya Industries,1,...,Atlanta Reign,Boston Uprising,0.000000,0.000000,0.000000,0.000000,NaN,NaN,1,0
5947,8/25/2019 21:09,8/25/2019 21:11,Overwatch League Stage 4,21446,2,Atlanta Reign,Atlanta Reign,Boston Uprising,Volskaya Industries,2,...,Atlanta Reign,Boston Uprising,0.000000,0.000000,291.655029,0.000000,NaN,NaN,2,1
5948,8/25/2019 21:25,8/25/2019 21:33,Overwatch League Stage 4,21446,3,Atlanta Reign,Atlanta Reign,Boston Uprising,King's Row,1,...,Atlanta Reign,Boston Uprising,66.917534,0.000000,0.000000,0.000000,NaN,NaN,2,0
5949,8/25/2019 21:37,8/25/2019 21:43,Overwatch League Stage 4,21446,3,Atlanta Reign,Atlanta Reign,Boston Uprising,King's Row,2,...,Atlanta Reign,Boston Uprising,66.921326,66.917534,86.403000,0.000000,NaN,NaN,3,2
5950,8/25/2019 21:49,8/25/2019 21:58,Overwatch League Stage 4,21446,4,Atlanta Reign,Atlanta Reign,Boston Uprising,Junkertown,1,...,Atlanta Reign,Boston Uprising,96.474075,0.000000,0.000000,0.000000,NaN,NaN,2,0
5951,8/25/2019 22:00,8/25/2019 22:08,Overwatch League Stage 4,21446,4,Atlanta Reign,Atlanta Reign,Boston Uprising,Junkertown,2,...,Atlanta Reign,Boston Uprising,96.486176,96.474075,0.000000,0.000000,NaN,NaN,3,2
5952,8/25/2019 22:25,8/25/2019 22:29,Overwatch League Stage 4,21513,1,Vancouver Titans,Vancouver Titans,New York Excelsior,Ilios,1,...,New York Excelsior,Vancouver Titans,0.000000,0.000000,0.000000,0.000000,48.0,100.0,0,1
5953,8/25/2019 22:30,8/25/2019 22:34,Overwatch League Stage 4,21513,1,Vancouver Titans,Vancouver Titans,New York Excelsior,Ilios,2,...,New York Excelsior,Vancouver Titans,0.000000,0.000000,0.000000,0.000000,73.0,100.0,0,2
5954,8/25/2019 22:42,8/25/2019 22:47,Overwatch League Stage 4,21513,2,Vancouver Titans,New York Excelsior,Vancouver Titans,Hanamura,1,...,Vancouver Titans,New York Excelsior,0.000000,0.000000,152.144013,0.000000,NaN,NaN,2,0
5955,8/25/2019 22:50,8/25/2019 22:57,Overwatch League Stage 4,21513,2,Vancouver Titans,New York Excelsior,Vancouver Titans,Hanamura,2,...,Vancouver Titans,New York Excelsior,0.000000,0.000000,0.000000,152.144013,NaN,NaN,1,2
5956,8/25/2019 23:13,8/25/2019 23:27,Overwatch League Stage 4,21513,3,Vancouver Titans,Vancouver Titans,New York Excelsior,Blizzard World,1,...,Vancouver Titans,New York Excelsior,78.657166,0.000000,0.000000,0.000000,NaN,NaN,2,0
5957,8/25/2019 23:30,8/25/2019 23:36,Overwatch League Stage 4,21513,3,Vancouver Titans,Vancouver Titans,New York Excelsior,Blizzard World,2,...,Vancouver Titans,New York Excelsior,78.665276,78.657166,120.510055,0.000000,NaN,NaN,3,2
5958,8/25/2019 23:42,8/25/2019 23:48,Overwatch League Stage 4,21513,4,Vancouver Titans,New York Excelsior,Vancouver Titans,Havana,1,...,Vancouver Titans,New York Excelsior,103.357452,0.000000,99.639999,0.000000,NaN,NaN,3,0
5959,8/25/2019 23:54,8/26/2019 0:02,Overwatch League Stage 4,21513,4,Vancouver Titans,New York Excelsior,Vancouver Titans,Havana,2,...,Vancouver Titans,New York Excelsior,95.479401,103.357452,0.000000,99.639999,NaN,NaN,2,3
5960,8/26/2019 0:08,8/26/2019 0:13,Overwatch League Stage 4,21513,5,Vancouver Titans,Vancouver Titans,New York Excelsior,Lijiang Tower,1,...,New York Excelsior,Vancouver Titans,0.000000,0.000000,0.000000,0.000000,100.0,99.0,1,0
5961,8/26/2019 0:14,8/26/2019 0:16,Overwatch League Stage 4,21513,5,Vancouver Titans,Vancouver Titans,New York Excelsior,Lijiang Tower,2,...,New York Excelsior,Vancouver Titans,0.000000,0.000000,0.000000,0.000000,0.0,100.0,1,1
5962,8/26/2019 0:17,8/26/2019 0:21,Overwatch League Stage 4,21513,5,Vancouver Titans,Vancouver Titans,New York Excelsior,Lijiang Tower,3,...,New York Excelsior,Vancouver Titans,0.000000,0.000000,0.000000,0.000000,38.0,100.0,1,2
5963,8/26/2019 0:39,8/26/2019 0:46,Overwatch League Stage 4,21515,1,San Francisco Shock,San Francisco Shock,Los Angeles Valiant,Lijiang Tower,1,...,San Francisco Shock,Los Angeles Valiant,0.000000,0.000000,0.000000,0.000000,100.0,99.0,1,0
5964,8/26/2019 0:46,8/26/2019 0:51,Overwatch League Stage 4,21515,1,San Francisco Shock,San Francisco Shock,Los Angeles Valiant,Lijiang Tower,2,...,San Francisco Shock,Los Angeles Valiant,0.000000,0.000000,0.000000,0.000000,100.0,48.0,2,0
5965,8/26/2019 0:58,8/26/2019 1:00,Overwatch League Stage 4,21515,2,San Francisco Shock,San Francisco Shock,Los Angeles Valiant,Volskaya Industries,1,...,Los Angeles Valiant,San Francisco Shock,0.000000,0.000000,261.442017,0.000000,NaN,NaN,2,0
5966,8/26/2019 1:03,8/26/2019 1:11,Overwatch League Stage 4,21515,2,San Francisco Shock,San Francisco Shock,Los Angeles Valiant,Volskaya Industries,2,...,Los Angeles Valiant,San Francisco Shock,0.000000,0.000000,0.000000,261.442017,NaN,NaN,1,2
5967,8/26/2019 1:24,8/26/2019 1:28,Overwatch League Stage 4,21515,3,San Francisco Shock,San Francisco Shock,Los Angeles Valiant,Blizzard World,1,...,Los Angeles Valiant,San Francisco Shock,111.613068,0.000000,232.570023,0.000000,NaN,NaN,3,0
5968,8/26/2019 1:31,8/26/2019 1:39,Overwatch League Stage 4,21515,3,San Francisco Shock,San Francisco Shock,Los Angeles Valiant,Blizzard World,2,...,Los Angeles Valiant,San Francisco Shock,106.249855,111.613068,0.000000,232.570023,NaN,NaN,2,3
5969,8/26/2019 1:48,8/26/2019 1:55,Overwatch League Stage 4,21515,4,San Francisco Shock,San Francisco Shock,Los Angeles Valiant,Junkertown,1,...,San Francisco Shock,Los Angeles Valiant,83.247345,0.000000,0.000000,0.000000,NaN,NaN,1,0
5970,8/26/2019 1:56,8/26/2019 1:59,Overwatch League Stage 4,21515,4,San Francisco Shock,San Francisco Shock,Los Angeles Valiant,Junkertown,2,...,San Francisco Shock,Los Angeles Valiant,83.254684,83.247345,200.770996,0.000000,NaN,NaN,2,1

In [11]:
#Splits dataframe into each individual game
games = []
for k, d in df.groupby("match_id"):
    games.append(d)
    
columns = ['id', 'date', 'stage', 'winning_team','winner_score', 'loser_score', 'losing_team']
allgames = []
#Iterates through the games to narrow data
for i in games:
    maps = []
    winner_score = 0
    loser_score = 0
    colu = ["name", "type", "winner", "winner_score", "loser_score", "loser"]
    date = i.round_start_time.iloc[0]
    stage = i.stage.iloc[0]
    matchid = i.match_id.iloc[0]
    winning_team = i.match_winner.iloc[0]
    if winning_team == i.map_winner.iloc[0]:
        losing_team = i.map_loser.iloc[0]
    else:
        losing_team = i.map_winner.iloc[0]
    for k, d in i.groupby("game_number"):
        mapa = d.iloc[0]
        map_number = mapa.game_number
        map_name = mapa.map_name
        if map_name == "Lijiang Tower":
            map_type = "Control"
        elif map_name == "Temple of Anubis":
            map_type = "Assault"
        elif map_name =="Watchpoint: Gibraltar":
            map_type = "Escort"
        else:
            map_type = MAP_TYPE.get(map_name)
        map_winner = mapa.map_winner
        map_loser = mapa.map_loser
        map_winner_score = mapa.winning_team_final_map_score
        map_loser_score = mapa.losing_team_final_map_score
        colum = ["map_"+str(map_number)+"_"+j for j in colu]
        mapdata = pd.Series([map_name, map_type, map_winner, map_winner_score, map_loser_score, map_loser], colum)
        maps.append(mapdata)
        if map_winner == winning_team:
            winner_score += 1
        elif map_winner == losing_team:
            loser_score += 1
        else:
            continue
    data = pd.Series([matchid, date, stage, winning_team, winner_score, loser_score, losing_team], columns)
    for item in maps:
        data = pd.concat([data, item])
        
    allgames.append(data)
    
gamers = pd.DataFrame(allgames)
gamers = gamers.set_index("id")
gamers["date"]=pd.to_datetime(gamers.date)
gamers = gamers.sort_values(by="date")
gamers

,date,stage,winning_team,winner_score,loser_score,losing_team,map_1_name,map_1_type,map_1_winner,map_1_winner_score,...,map_6_winner,map_6_winner_score,map_6_loser_score,map_6_loser,map_7_name,map_7_type,map_7_winner,map_7_winner_score,map_7_loser_score,map_7_loser
id,,,,,,,,,,,,,,,,,,,,,
21211,2019-02-15 00:11:00,Overwatch League Stage 1,Philadelphia Fusion,3,1,London Spitfire,Ilios,Control,Philadelphia Fusion,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21221,2019-02-15 01:54:00,Overwatch League Stage 1,New York Excelsior,2,1,Boston Uprising,Nepal,Control,New York Excelsior,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21231,2019-02-15 03:46:00,Overwatch League Stage 1,Seoul Dynasty,3,1,Los Angeles Gladiators,Ilios,Control,Los Angeles Gladiators,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21176,2019-02-15 05:26:00,Overwatch League Stage 1,Hangzhou Spark,3,1,Shanghai Dragons,Busan,Control,Hangzhou Spark,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21177,2019-02-16 00:05:00,Overwatch League Stage 1,Toronto Defiant,3,2,Houston Outlaws,Nepal,Control,Houston Outlaws,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21241,2019-02-16 02:19:00,Overwatch League Stage 1,Atlanta Reign,4,0,Florida Mayhem,Ilios,Control,Atlanta Reign,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21126,2019-02-16 04:03:00,Overwatch League Stage 1,San Francisco Shock,4,0,Dallas Fuel,Nepal,Control,San Francisco Shock,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21212,2019-02-16 05:38:00,Overwatch League Stage 1,Chengdu Hunters,3,2,Guangzhou Charge,Busan,Control,Guangzhou Charge,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21209,2019-02-16 20:06:00,Overwatch League Stage 1,Paris Eternal,3,1,London Spitfire,Ilios,Control,Paris Eternal,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21127,2019-02-16 21:33:00,Overwatch League Stage 1,New York Excelsior,3,1,Washington Justice,Ilios,Control,New York Excelsior,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21251,2019-02-16 22:53:00,Overwatch League Stage 1,Hangzhou Spark,3,2,Los Angeles Valiant,Busan,Control,Hangzhou Spark,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21222,2019-02-17 01:01:00,Overwatch League Stage 1,Vancouver Titans,4,0,Shanghai Dragons,Busan,Control,Vancouver Titans,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21213,2019-02-17 20:07:00,Overwatch League Stage 1,Boston Uprising,3,2,Houston Outlaws,Nepal,Control,Houston Outlaws,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21261,2019-02-17 22:09:00,Overwatch League Stage 1,Philadelphia Fusion,3,2,Atlanta Reign,Nepal,Control,Atlanta Reign,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21128,2019-02-18 00:13:00,Overwatch League Stage 1,Los Angeles Gladiators,3,2,San Francisco Shock,Ilios,Control,San Francisco Shock,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21271,2019-02-18 02:27:00,Overwatch League Stage 1,Dallas Fuel,3,1,Seoul Dynasty,Busan,Control,Dallas Fuel,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21210,2019-02-22 00:05:00,Overwatch League Stage 1,London Spitfire,3,2,Washington Justice,Busan,Control,Washington Justice,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21232,2019-02-22 02:08:00,Overwatch League Stage 1,Florida Mayhem,2,1,Philadelphia Fusion,Nepal,Control,Florida Mayhem,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21272,2019-02-22 03:46:00,Overwatch League Stage 1,Guangzhou Charge,4,0,Dallas Fuel,Busan,Control,Guangzhou Charge,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21233,2019-02-22 05:19:00,Overwatch League Stage 1,Seoul Dynasty,4,0,Chengdu Hunters,Ilios,Control,Seoul Dynasty,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21178,2019-02-23 00:05:00,Overwatch League Stage 1,Atlanta Reign,3,1,Toronto Defiant,Busan,Control,Toronto Defiant,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21242,2019-02-23 01:53:00,Overwatch League Stage 1,New York Excelsior,3,2,Los Angeles Valiant,Nepal,Control,Los Angeles Valiant,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21281,2019-02-23 03:33:00,Overwatch League Stage 1,Shanghai Dragons,3,1,Boston Uprising,Ilios,Control,Shanghai Dragons,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21179,2019-02-23 05:15:00,Overwatch League Stage 1,Houston Outlaws,3,1,Hangzhou Spark,Busan,Control,Houston Outlaws,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21243,2019-02-23 20:05:00,Overwatch League Stage 1,Paris Eternal,2,1,Los Angeles Gladiators,Nepal,Control,Los Angeles Gladiators,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21282,2019-02-23 21:47:00,Overwatch League Stage 1,Dallas Fuel,3,1,Philadelphia Fusion,Busan,Control,Dallas Fuel,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21291,2019-02-23 23:25:00,Overwatch League Stage 1,Vancouver Titans,3,2,Guangzhou Charge,Nepal,Control,Guangzhou Charge,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21234,2019-02-24 01:24:00,Overwatch League Stage 1,Chengdu Hunters,3,2,Florida Mayhem,Nepal,Control,Chengdu Hunters,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21301,2019-02-24 20:05:00,Overwatch League Stage 1,London Spitfire,3,1,Hangzhou Spark,Ilios,Control,London Spitfire,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21235,2019-02-24 21:35:00,Overwatch League Stage 1,New York Excelsior,4,0,Houston Outlaws,Nepal,Control,New York Excelsior,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21426,2019-08-10 20:37:00,Overwatch League Stage 4,Seoul Dynasty,2,1,Toronto Defiant,Lijiang Tower,Control,Seoul Dynasty,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21456,2019-08-10 22:23:00,Overwatch League Stage 4,Los Angeles Valiant,2,1,Florida Mayhem,Ilios,Control,Los Angeles Valiant,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21463,2019-08-11 00:06:00,Overwatch League Stage 4,Hangzhou Spark,3,1,Chengdu Hunters,Ilios,Control,Chengdu Hunters,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21492,2019-08-11 19:07:00,Overwatch League Stage 4,Vancouver Titans,4,0,Philadelphia Fusion,Busan,Control,Vancouver Titans,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21483,2019-08-11 20:57:00,Overwatch League Stage 4,Washington Justice,3,2,Houston Outlaws,Lijiang Tower,Control,Houston Outlaws,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21502,2019-08-11 23:06:00,Overwatch League Stage 4,San Francisco Shock,4,0,Dallas Fuel,Ilios,Control,San Francisco Shock,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21437,2019-08-12 00:42:00,Overwatch League Stage 4,Guangzhou Charge,4,0,New York Excelsior,Lijiang Tower,Control,Guangzhou Charge,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21410,2019-08-15 23:06:00,Overwatch League Stage 4,Florida Mayhem,4,0,Boston Uprising,Ilios,Control,Florida Mayhem,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21457,2019-08-16 00:45:00,Overwatch League Stage 4,Hangzhou Spark,3,1,Dallas Fuel,Lijiang Tower,Control,Dallas Fuel,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21427,2019-08-16 02:30:00,Overwatch League Stage 4,Seoul Dynasty,3,1,Shanghai Dragons,Ilios,Control,Seoul Dynasty,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21458,2019-08-16 23:06:00,Overwatch League Stage 4,Atlanta Reign,2,1,Washington Justice,Busan,Control,Atlanta Reign,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21464,2019-08-17 00:43:00,Overwatch League Stage 4,San Francisco Shock,4,0,Chengdu Hunters,Ilios,Control,San Francisco Shock,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21484,2019-08-17 02:10:00,Overwatch League Stage 4,Hangzhou Spark,3,2,Los Angeles Gladiators,Busan,Control,Los Angeles Gladiators,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21493,2019-08-17 19:06:00,Overwatch League Stage 4,Paris Eternal,3,1,Shanghai Dragons,Lijiang Tower,Control,Paris Eternal,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21503,2019-08-17 20:51:00,Overwatch League Stage 4,Los Angeles Valiant,3,1,Boston Uprising,Busan,Control,Los Angeles Valiant,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21428,2019-08-17 22:39:00,Overwatch League Stage 4,Philadelphia Fusion,3,1,Seoul Dynasty,Lijiang Tower,Control,Philadelphia Fusion,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21459,2019-08-18 00:13:00,Overwatch League Stage 4,Chengdu Hunters,3,2,Houston Outlaws,Ilios,Control,Houston Outlaws,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21504,2019-08-18 19:07:00,Overwatch League Stage 4,Atlanta Reign,4,0,London Spitfire,Busan,Control,Atlanta Reign,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21465,2019-08-18 20:46:00,Overwatch League Stage 4,Washington Justice,3,1,Paris Eternal,Ilios,Control,Washington Justice,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21460,2019-08-18 22:37:00,Overwatch League Stage 4,Florida Mayhem,4,0,Toronto Defiant,Busan,Control,Florida Mayhem,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21512,2019-08-19 00:34:00,Overwatch League Stage 4,Guangzhou Charge,4,0,Dallas Fuel,Ilios,Control,Guangzhou Charge,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21485,2019-08-24 21:07:00,Overwatch League Stage 4,Atlanta Reign,3,1,Dallas Fuel,Busan,Control,Atlanta Reign,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21494,2019-08-24 23:01:00,Overwatch League Stage 4,New York Excelsior,3,1,Boston Uprising,Ilios,Control,New York Excelsior,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21521,2019-08-25 00:47:00,Overwatch League Stage 4,San Francisco Shock,3,2,Vancouver Titans,Lijiang Tower,Control,Vancouver Titans,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21419,2019-08-25 02:59:00,Overwatch League Stage 4,Los Angeles Gladiators,3,1,Los Angeles Valiant,Ilios,Control,Los Angeles Valiant,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21514,2019-08-25 19:08:00,Overwatch League Stage 4,Hangzhou Spark,4,0,Shanghai Dragons,Busan,Control,Hangzhou Spark,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21446,2019-08-25 20:46:00,Overwatch League Stage 4,Atlanta Reign,4,0,Boston Uprising,Lijiang Tower,Control,Atlanta Reign,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21513,2019-08-25 22:25:00,Overwatch League Stage 4,Vancouver Titans,3,2,New York Excelsior,Ilios,Control,Vancouver Titans,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21515,2019-08-26 00:39:00,Overwatch League Stage 4,San Francisco Shock,4,0,Los Angeles Valiant,Lijiang Tower,Control,San Francisco Shock,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21352,NaT,Overwatch League Stage 2,London Spitfire,4,0,Paris Eternal,Busan,Control,London Spitfire,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
teamnames = ['Atlanta Reign', 'Boston Uprising', 'Chengdu Hunters', 'Dallas Fuel', 'Florida Mayhem', 
             'Guangzhou Charge', 'Hangzhou Spark', 'Houston Outlaws', 'London Spitfire', 'Los Angeles Gladiators', 
             'Los Angeles Valiant', 'New York Excelsior', 'Paris Eternal', 'Philadelphia Fusion', 'San Francisco Shock', 
             'Seoul Dynasty', 'Shanghai Dragons', 'Toronto Defiant', 'Vancouver Titans', 'Washington Justice']
team_series = []

#Filtering Dataframe to numerical data
colums = ["winning_team", "winner_score", "losing_team","loser_score",
          "map_1_name", "map_1_type", "map_1_winner", "map_1_winner_score", "map_1_loser_score", "map_1_loser",
          "map_2_name", "map_2_type", "map_2_winner", "map_2_winner_score", "map_2_loser_score", "map_2_loser",
          "map_3_name", "map_3_type", "map_3_winner", "map_3_winner_score", "map_3_loser_score", "map_3_loser",
          "map_4_name", "map_4_type", "map_4_winner", "map_4_winner_score", "map_4_loser_score", "map_4_loser", 
          "map_5_name", "map_5_type", "map_5_winner", "map_5_winner_score", "map_5_loser_score", "map_5_loser"]

df = gamers[colums]

#Columns that will be recorded
map_colums = ["wins" , "losses", "draws", "times_played", "average_points_earned", 
              "average_points_lost", "average_points_differential", "win_perc", "true_perc", "map_potential_perc"]

#iterates through each team and collects all map statistics
for i in teamnames:
    control = []
    assault = []
    hybrid = []
    escort = []
    teamdf = df[df.eq(i).any(1)]
    for index, row in teamdf.iterrows():
        for column in row.iteritems():
            if column[0].find("type") > -1:
                map_name = column[0].replace("_type", "")
                if isinstance(column[1], str):
                    index = ["name", "type", "winner", "winner_score", "loser_score", "loser"]
                    if column[1].find("Control") > -1:
                        data = row[(map_name + "_name"):(map_name + "_loser")]
                        data.index = index
                        control.append(data)
                    elif column[1].find("Assault") > -1:
                        data = row[(map_name + "_name"):(map_name + "_loser")]
                        data.index = index
                        assault.append(data)
                    elif column[1].find("Hybrid") > -1:
                        data = row[(map_name + "_name"):(map_name + "_loser")]
                        data.index = index
                        hybrid.append(data)
                    elif column[1].find("Escort") > -1:
                        data = row[(map_name + "_name"):(map_name + "_loser")]
                        data.index = index
                        escort.append(data)
                    else:
                        continue
    #Assault
    hanamura = []
    horizon = []
    paris = []
    temple = []
    volskaya = []
    
    #Control
    busan = []
    ilios = []
    lijiang = []
    nepal = []
    oasis = []
    
    #Hybrid
    blizzard = []
    eichenwalde = []
    hollywood = []
    king = []
    numbani = []
    
    #Escort
    dorado = []
    havana = []
    junkertown = []
    rialto = []
    route = []
    gibraltar = []
    
    def get_stats(thelist):
        name = thelist[0]["name"]
        loss = round(0, 3)
        win = round(0, 3)
        draw = round(0, 3)
        points_earned = round(0, 3)
        points_given = round(0, 3)
        map_potential = round(0, 3)

        total = len(thelist)
        for game in thelist:
            if game.winner != i:
                if game.winner == "draw":
                    draw += 1
                    points_earned += game.loser_score
                    points_given += game.winner_score
                    pwon = game.loser_score
                    plos = game.winner_score
                else:
                    loss += 1
                    points_earned += game.loser_score
                    points_given += game.winner_score
                    pwon = game.loser_score
                    plos = game.winner_score
                    
            else:
                win += 1
                points_earned += game.winner_score
                points_given += game.loser_score
                pwon = game.loser_score
                plos = game.winner_score

            if pwon > plos:
                map_potential += 1
            else:
                try:
                    map_potential += (pwon / plos)
                except ZeroDivisionError:
                    map_potential += 0

        win_per = round((win / total) * 100, 3)
        true_per = round(((win + (draw / 2)) / total) * 100, 3)
        avg_points_earned = round(points_earned / total, 3)
        avg_points_given = round(points_given / total, 3)
        avg_point_diff = round(avg_points_earned - avg_points_given, 3)
        true_map_potential = round(map_potential / total, 3)
        
        colums = [name + "_" + w for w in map_colums]

        map_data = pd.Series([win, loss, draw, total,
                              avg_points_earned, avg_points_given, avg_point_diff, win_per, true_per, 
                              true_map_potential], colums)
        return map_data
            
    for j in assault:
        if j["name"].find("Hanamura") > -1:
            hanamura.append(j)
        elif j["name"].find("Horizon Lunar Colony") > -1:
            horizon.append(j)
        elif j["name"].find("Paris") > -1:
            paris.append(j)
        elif j["name"].find("Temple of Anubis") > -1:
            temple.append(j)
        elif j["name"].find("Volskaya Industries") > -1:
            volskaya.append(j)
        else:
            continue
    assault_data = pd.concat([get_stats(hanamura), 
                              get_stats(horizon), 
                              get_stats(paris),
                              get_stats(temple),
                              get_stats(volskaya)])

    for j in control:
        if j["name"].find("Busan") > -1:
            busan.append(j)
        elif j["name"].find("Ilios") > -1:
            ilios.append(j)
        elif j["name"].find("Lijiang Tower") > -1:
            lijiang.append(j)
        elif j["name"].find("Nepal") > -1:
            nepal.append(j)
        elif j["name"].find("Oasis") > -1:
            oasis.append(j)
        else:
            continue
    control_data = pd.concat([get_stats(busan),
                              get_stats(ilios), 
                              get_stats(lijiang), 
                              get_stats(nepal), 
                              get_stats(oasis)
                             ])

    for j in hybrid:
        if j["name"].find("Blizzard World") > -1:
            blizzard.append(j)
        elif j["name"].find("Eichenwalde") > -1:
            eichenwalde.append(j)
        elif j["name"].find("Hollywood") > -1:
            hollywood.append(j)
        elif j["name"].find("King's Row") > -1:
            king.append(j)
        elif j["name"].find("Numbani") > -1:
            numbani.append(j)
        else:
            continue
    hybrid_data = pd.concat([get_stats(blizzard),
                             get_stats(eichenwalde),
                             get_stats(hollywood),
                             get_stats(king),
                             get_stats(numbani)])

    for j in escort:
        if j["name"].find("Dorado") > -1:
            dorado.append(j)
        elif j["name"].find("Havana") > -1:
            havana.append(j)
        elif j["name"].find("Junkertown") > -1:
            junkertown.append(j)
        elif j["name"].find("Rialto") > -1:
            rialto.append(j)
        elif j["name"].find("Route 66") > -1:
            route.append(j)
        elif j["name"].find("Watchpoint: Gibraltar") > -1:
            gibraltar.append(j)
        else:
            continue
    escort_data = pd.concat([get_stats(dorado),
                             get_stats(havana),
                             get_stats(junkertown),
                             get_stats(rialto),
                             get_stats(route),
                             get_stats(gibraltar)])
    
    complete_data = pd.concat([assault_data, control_data, hybrid_data, escort_data])
    team_name = pd.Series(i, index = ["Team Name"])
    complete_data = pd.concat([team_name, complete_data])
    team_series.append(complete_data)

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\ops.py:1649: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  result = method(y)

In [13]:
#Turn data into dataframe
datadf = pd.DataFrame(team_series)

#Assign map names to each series of data
map_names = ["Busan","Ilios","Lijiang Tower","Nepal","Oasis",
             "Hanamura","Horizon Lunar Colony","Paris","Temple of Anubis","Volskaya Industries",
             "Blizzard World","Eichenwalde","Hollywood","King's Row","Numbani",
             "Dorado","Havana","Junkertown","Rialto","Route 66","Watchpoint: Gibraltar"]

#Adds Percentages and Rankings for each team
for stringtest in map_names:
    wincol = datadf[stringtest+"_win_perc"].rank(ascending = False, method = "min")
    truecol = datadf[stringtest+"_true_perc"].rank(ascending = False, method = "min")
    mappolcol = datadf[stringtest+"_map_potential_perc"].rank(ascending = False, method = "min")
    datadf.insert(datadf.columns.get_loc(stringtest+"_win_perc") + 1, stringtest+"_win_perc_rank", wincol )
    datadf.insert(datadf.columns.get_loc(stringtest+"_true_perc") + 1, stringtest+"_true_perc_rank", truecol )
    datadf.insert(datadf.columns.get_loc(stringtest+"_map_potential_perc") + 1, stringtest+"_map_potential_perc_rank", mappolcol )
datadf.filter(regex = " ")

,Team Name,Horizon Lunar Colony_wins,Horizon Lunar Colony_losses,Horizon Lunar Colony_draws,Horizon Lunar Colony_times_played,Horizon Lunar Colony_average_points_earned,Horizon Lunar Colony_average_points_lost,Horizon Lunar Colony_average_points_differential,Horizon Lunar Colony_win_perc,Horizon Lunar Colony_win_perc_rank,...,Watchpoint: Gibraltar_times_played,Watchpoint: Gibraltar_average_points_earned,Watchpoint: Gibraltar_average_points_lost,Watchpoint: Gibraltar_average_points_differential,Watchpoint: Gibraltar_win_perc,Watchpoint: Gibraltar_win_perc_rank,Watchpoint: Gibraltar_true_perc,Watchpoint: Gibraltar_true_perc_rank,Watchpoint: Gibraltar_map_potential_perc,Watchpoint: Gibraltar_map_potential_perc_rank
0,Atlanta Reign,3.0,2.0,0.0,5.0,2.200,1.800,0.400,60.000,7.0,...,4.0,3.750,4.750,-1.000,0.000,18.0,0.000,18.0,0.783,1.0
1,Boston Uprising,2.0,2.0,1.0,5.0,3.000,3.000,0.000,40.000,12.0,...,4.0,2.500,3.250,-0.750,25.000,15.0,25.000,15.0,0.525,6.0
2,Chengdu Hunters,2.0,2.0,0.0,4.0,2.250,2.250,0.000,50.000,11.0,...,4.0,2.500,1.500,1.000,75.000,4.0,75.000,4.0,0.271,16.0
3,Dallas Fuel,0.0,3.0,1.0,4.0,2.250,3.000,-0.750,0.000,19.0,...,4.0,2.500,3.500,-1.000,25.000,15.0,25.000,15.0,0.554,4.0
4,Florida Mayhem,0.0,5.0,0.0,5.0,2.600,3.600,-1.000,0.000,19.0,...,4.0,1.250,1.750,-0.500,50.000,9.0,50.000,9.0,0.292,14.0
5,Guangzhou Charge,4.0,0.0,0.0,4.0,3.250,2.250,1.000,100.000,1.0,...,6.0,1.833,2.333,-0.500,33.333,14.0,33.333,14.0,0.375,10.0
6,Hangzhou Spark,2.0,2.0,1.0,5.0,2.400,2.600,-0.200,40.000,12.0,...,6.0,2.333,1.667,0.666,66.667,6.0,66.667,6.0,0.431,9.0
7,Houston Outlaws,2.0,3.0,0.0,5.0,1.400,1.600,-0.200,40.000,12.0,...,4.0,2.000,3.500,-1.500,0.000,18.0,0.000,18.0,0.542,5.0
8,London Spitfire,3.0,2.0,0.0,5.0,2.400,1.800,0.600,60.000,7.0,...,5.0,1.600,1.800,-0.200,60.000,7.0,60.000,7.0,0.283,15.0
9,Los Angeles Gladiators,3.0,2.0,0.0,5.0,2.000,1.600,0.400,60.000,7.0,...,5.0,1.400,1.800,-0.400,40.000,13.0,40.000,13.0,0.217,19.0
10,Los Angeles Valiant,1.0,5.0,0.0,6.0,2.167,2.833,-0.666,16.667,17.0,...,4.0,1.000,0.750,0.250,50.000,9.0,50.000,9.0,0.000,20.0
11,New York Excelsior,3.0,1.0,1.0,5.0,1.600,1.200,0.400,60.000,7.0,...,5.0,2.000,1.600,0.400,80.000,3.0,80.000,3.0,0.350,12.0
12,Paris Eternal,1.0,4.0,0.0,5.0,2.000,2.600,-0.600,20.000,16.0,...,4.0,3.750,3.750,0.000,50.000,9.0,50.000,9.0,0.721,2.0
13,Philadelphia Fusion,4.0,2.0,0.0,6.0,2.167,2.000,0.167,66.667,6.0,...,5.0,1.800,1.200,0.600,60.000,7.0,60.000,7.0,0.267,17.0
14,San Francisco Shock,6.0,2.0,0.0,8.0,3.125,2.500,0.625,75.000,3.0,...,7.0,3.286,1.429,1.857,100.000,1.0,100.000,1.0,0.329,13.0
15,Seoul Dynasty,3.0,1.0,0.0,4.0,2.500,2.000,0.500,75.000,3.0,...,4.0,4.000,3.250,0.750,75.000,4.0,75.000,4.0,0.671,3.0
16,Shanghai Dragons,4.0,1.0,0.0,5.0,3.800,3.200,0.600,80.000,2.0,...,6.0,1.500,1.333,0.167,50.000,9.0,50.000,9.0,0.264,18.0
17,Toronto Defiant,1.0,5.0,0.0,6.0,2.333,3.167,-0.834,16.667,17.0,...,4.0,2.000,3.500,-1.500,25.000,15.0,25.000,15.0,0.375,10.0
18,Vancouver Titans,3.0,1.0,0.0,4.0,2.250,1.750,0.500,75.000,3.0,...,6.0,3.500,2.333,1.167,83.333,2.0,83.333,2.0,0.475,8.0
19,Washington Justice,1.0,3.0,0.0,4.0,1.250,2.250,-1.000,25.000,15.0,...,5.0,1.600,3.000,-1.400,0.000,18.0,0.000,18.0,0.517,7.0

In [14]:
#renaming for writeability
stats= datadf

#clearing all previous items in list, as the list is reused
assault.clear()
control.clear()
hybrid.clear()
escort.clear()

#creating new specific lists
times_played = []
earned = []
lost = []
differ = []
winperc = []
trueperc = []
cows = []

#filtering maps based on map type
for i in stats.columns:
    if re.search("Hanamura\B", i) or re.search("Horizon Lunar Colony\B", i) or re.search("Paris\B", i) or re.search("Temple of Anubis\B", i) or re.search("Volskaya Industries\B", i):
        assault.append(i)
    elif re.search("Busan\B", i) or re.search("Ilios\B", i) or re.search("Lijiang Tower\B", i) or re.search("Nepal\B", i) or re.search("Oasis\B", i):
        control.append(i)
    elif re.search("Blizzard World\B", i) or re.search("Eichenwalde\B", i) or re.search("Hollywood\B", i) or re.search("King's Row\B", i) or re.search("Numbani\B", i):
        hybrid.append(i)
    elif re.search("Dorado\B", i) or re.search("Havana\B", i) or re.search("Junkertown\B", i) or re.search("Rialto\B", i) or re.search("Route 66\B", i) or re.search("Watchpoint: Gibraltar\B", i):
        escort.append(i)
    else:
        continue

#helper function to aggregate data across the map type, and returns statictics
def sum_rows(maptype, name): 
    times_played = [i for i in maptype if "times_played" in i]
    times_playedtotal = stats[times_played].sum(axis = 1)
    
    wins = [i for i in maptype if "wins" in i]
    winstotal = stats[wins].sum(axis = 1)
        
    loss = [i for i in maptype if "losses" in i]
    losstotal = stats[loss].sum(axis = 1)
    
    draw = [i for i in maptype if "draws" in i]
    drawtotal = stats[draw].sum(axis = 1)
    
    earned = [i for i in maptype if "average_points_earned" in i]
    earnedtotal = stats[earned].mean(axis = 1)
    
    lost = [i for i in maptype if "average_points_lost" in i]
    losttotal = stats[lost].mean(axis = 1)
    
    differ = [i for i in maptype if "average_points_differential" in i]
    differtotal = stats[differ].mean(axis = 1)
    sa = pd.DataFrame(data = differtotal)
    sa["total"] = differtotal
    differrank = sa["total"].rank(ascending = False, method = "min")
    
    winperctotal = (winstotal/times_playedtotal) * 100
    sa["total"] = winperctotal
    winpercrank = sa["total"].rank(ascending = False, method = "min")
    
    trueperctotal = ((winstotal + (drawtotal / 2)) / times_playedtotal) * 100
    sa["total"] = trueperctotal
    truepercrank = sa["total"].rank(ascending = False, method = "min")
    
    cows = [i for i in maptype if "map_potential_perc" in i and "Rank" not in i]
    cowstotal = stats[cows].mean(axis = 1)
    sa["total"] = cowstotal
    cowsrank = sa["total"].rank(ascending = False, method = "min")
    
    if name == "Assault":
        stats.insert(stats.columns.get_loc("Volskaya Industries_map_potential_perc_rank") + 1, "Total Assault Played", times_playedtotal)
        stats.insert(stats.columns.get_loc("Total Assault Played") + 1, "Average Assault Points Earned", earnedtotal)
        stats.insert(stats.columns.get_loc("Average Assault Points Earned") + 1, "Average Assault Points Lost", losttotal)
        stats.insert(stats.columns.get_loc("Average Assault Points Lost") + 1, "Average Assault Points Differential", differtotal)
        stats.insert(stats.columns.get_loc("Average Assault Points Differential") + 1, "Average Assault Points Differential Rank", differrank)
        stats.insert(stats.columns.get_loc("Average Assault Points Differential Rank") + 1, "Average Assault Win %", winperctotal)
        stats.insert(stats.columns.get_loc("Average Assault Win %") + 1, "Average Assault Win % Rank", winpercrank)
        stats.insert(stats.columns.get_loc("Average Assault Win % Rank") + 1, "Average Assault True Win %", trueperctotal)
        stats.insert(stats.columns.get_loc("Average Assault True Win %") + 1, "Average Assault True Win % Rank", truepercrank)
        stats.insert(stats.columns.get_loc("Average Assault True Win % Rank") + 1, "Average Assault Map Potential %", cowstotal)
        stats.insert(stats.columns.get_loc("Average Assault Map Potential %") + 1, "Average Assault Map Potential % Rank", cowsrank)
        
    elif name == "Control":
        stats.insert(stats.columns.get_loc("Oasis_map_potential_perc_rank") + 1, "Total Control Played", times_playedtotal)
        stats.insert(stats.columns.get_loc("Total Control Played") + 1, "Average Control Points Earned", earnedtotal)
        stats.insert(stats.columns.get_loc("Average Control Points Earned") + 1, "Average Control Points Lost", losttotal)
        stats.insert(stats.columns.get_loc("Average Control Points Lost") + 1, "Average Control Points Differential", differtotal)
        stats.insert(stats.columns.get_loc("Average Control Points Differential") + 1, "Average Control Points Differential Rank", differrank)
        stats.insert(stats.columns.get_loc("Average Control Points Differential Rank") + 1, "Average Control Win %", winperctotal)
        stats.insert(stats.columns.get_loc("Average Control Win %") + 1, "Average Control Win % Rank", winpercrank)
        stats.insert(stats.columns.get_loc("Average Control Win % Rank") + 1, "Average Control True Win %", trueperctotal)
        stats.insert(stats.columns.get_loc("Average Control True Win %") + 1, "Average Control True Win % Rank", truepercrank)
        stats.insert(stats.columns.get_loc("Average Control True Win % Rank") + 1, "Average Control Map Potential %", cowstotal)
        stats.insert(stats.columns.get_loc("Average Control Map Potential %") + 1, "Average Control Map Potential % Rank", cowsrank)
    
    elif name == "Hybrid":
        stats.insert(stats.columns.get_loc("Numbani_map_potential_perc_rank") + 1, "Total Hybrid Played", times_playedtotal)
        stats.insert(stats.columns.get_loc("Total Hybrid Played") + 1, "Average Hybrid Points Earned", earnedtotal)
        stats.insert(stats.columns.get_loc("Average Hybrid Points Earned") + 1, "Average Hybrid Points Lost", losttotal)
        stats.insert(stats.columns.get_loc("Average Hybrid Points Lost") + 1, "Average Hybrid Points Differential", differtotal)
        stats.insert(stats.columns.get_loc("Average Hybrid Points Differential") + 1, "Average Hybrid Points Differential Rank", differrank)
        stats.insert(stats.columns.get_loc("Average Hybrid Points Differential Rank") + 1, "Average Hybrid Win %", winperctotal)
        stats.insert(stats.columns.get_loc("Average Hybrid Win %") + 1, "Average Hybrid Win % Rank", winpercrank)
        stats.insert(stats.columns.get_loc("Average Hybrid Win % Rank") + 1, "Average Hybrid True Win %", trueperctotal)
        stats.insert(stats.columns.get_loc("Average Hybrid True Win %") + 1, "Average Hybrid True Win % Rank", truepercrank)
        stats.insert(stats.columns.get_loc("Average Hybrid True Win % Rank") + 1, "Average Hybrid Map Potential %", cowstotal)
        stats.insert(stats.columns.get_loc("Average Hybrid Map Potential %") + 1, "Average Hybrid Map Potential % Rank", cowsrank)
    
    elif name == "Escort":
        stats.insert(stats.columns.get_loc("Watchpoint: Gibraltar_map_potential_perc_rank") + 1, "Total Escort Played", times_playedtotal)
        stats.insert(stats.columns.get_loc("Total Escort Played") + 1, "Average Escort Points Earned", earnedtotal)
        stats.insert(stats.columns.get_loc("Average Escort Points Earned") + 1, "Average Escort Points Lost", losttotal)
        stats.insert(stats.columns.get_loc("Average Escort Points Lost") + 1, "Average Escort Points Differential", differtotal)
        stats.insert(stats.columns.get_loc("Average Escort Points Differential") + 1, "Average Escort Points Differential Rank", differrank)
        stats.insert(stats.columns.get_loc("Average Escort Points Differential Rank") + 1, "Average Escort Win %", winperctotal)
        stats.insert(stats.columns.get_loc("Average Escort Win %") + 1, "Average Escort Win % Rank", winpercrank)
        stats.insert(stats.columns.get_loc("Average Escort Win % Rank") + 1, "Average Escort True Win %", trueperctotal)
        stats.insert(stats.columns.get_loc("Average Escort True Win %") + 1, "Average Escort True Win % Rank", truepercrank)
        stats.insert(stats.columns.get_loc("Average Escort True Win % Rank") + 1, "Average Escort Map Potential %", cowstotal)
        stats.insert(stats.columns.get_loc("Average Escort Map Potential %") + 1, "Average Escort Map Potential % Rank", cowsrank)
        
    else:
        pass

sum_rows(assault, "Assault")
sum_rows(control, "Control")
sum_rows(hybrid, "Hybrid")
sum_rows(escort, "Escort")

In [15]:
#This is primarily a playoff check to remove teams who did not participate in playoffs or stage playoffs
stats = stats[np.isfinite(stats["Average Escort Win %"])]
stats = stats.set_index("Team Name")

#converts all data to a csv
stats.to_csv("statsnew.csv")